title: distributed.net
description: distributed.net theme test
# remote_theme: bovine/jekyll-theme-chirpy
# remote_theme: cotes2020/jekyll-theme-chirpy
theme: minima

header_pages:
  - index.md
  - projects.md
  - download.md
#  - news.md
#  - help.md
#  - discuss.md
#  - history.md
#  - donations.md
#  - credits.md

show_excerpts: true

minima:
  skin: "dnetgray"
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: twitter, user_url: "https://twitter.com/dnetc" }
    - { platform: facebook, user_url: "https://www.facebook.com/dnetc" }
    - { platform: github, user_url: "https://github.com/dcti" }
  
